### ISSUE TITLE
Enabled Debug Mode [Medium]

### ISSUE THREAD

**Issue by AyrtonBrincat** [mohammedGrech/Biometric-PasswordVaultManager#20]
ENABLED DEBUG MODE [Medium]

This is currently required while the application is still in development
Once the application is released, this item will be mitigated by changing android:debuggable="true" to android:debuggable="false".

Please refer to the ticket #028 on basecamp for the vulnerability assessment of the security consultant.
https://3.basecamp.com/5557999/buckets/31472726/card_tables/cards/5915678228

**Comment by mohammedGrech** [comment]
As you rightfully pointed out and as was mentioned by Karl, the debugging mode will remain on since from a development perspective, this should be kept on since it is required for testing. Once the app is released to the customer, the debug mode will be turned to false.

To set debug mode to false, the following script is required:

in the manifest file:
android:debuggable = "false"
tools:ignore="HardcodedDebugMode">

In the gradil.build file:
debug {
    debuggable true
    buildConfigField "Boolean", "DEBUG_MODE", "true"
}
release {
    buildConfigField "Boolean", "DEBUG_MODE", "false"
    debuggable false
    minifyEnabled false
    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

}
