### ISSUE TITLE
Reverse Engineering

### ISSUE THREAD

**Issue by AyrtonBrincat** [mohammedGrech/Biometric-PasswordVaultManager#5]
Methods to avoid reverse engineering: 
https://stackoverflow.com/questions/58297625/how-to-make-my-code-secure-and-prevent-from-decompiling
https://stackoverflow.com/questions/13854425/how-to-avoid-reverse-engineering-of-an-apk-file

Please refer to the ticket #025 on basecamp for the risk assessment of the security consultant.
https://3.basecamp.com/5557999/buckets/31472726/card_tables/cards/5909045847

**Comment by mohammedGrech** [comment]
As per our group discussion, reverse engineering shall be considered at a later stage due to the following reasons:

- There are tasks and implementations that are given a higher priority.
- Reverse engineering is implemented at the final stage of the product.

@Jmiffy97 kindly open a ticket for this item under the backlog for future implementation.
